#!/usr/bin/env python3
"""
Write fresh manual assessment for 1262_28-32.
Based on: taxonomy (7 categories, 5 framing), Russian original, segment list.
Never read GT labels. 1988 KGB report on special measures against foreign OUN centers.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SEGMENTS_PATH = ROOT / "data" / "output" / "segments_only_1262_28-32.json"
ASSESSMENTS_PATH = ROOT / "data" / "output" / "agent_assessments.json"

ASSESSMENT = {
    3: ("Documents", "Generic / Neutral Language"),
    4: ("Documents", "Generic / Neutral Language"),
    5: ("Time", "Generic / Neutral Language"),
    6: ("Places", "Generic / Neutral Language"),
    7: ("Context and Concepts", "Generic / Neutral Language"),
    8: ("Context and Concepts", "Generic / Neutral Language"),
    9: ("Time", "Generic / Neutral Language"),
    10: ("Context and Concepts", "Generic / Neutral Language"),
    11: ("Time", "Generic / Neutral Language"),
    12: ("Actors", "Generic / Neutral Language"),
    13: ("Actors", "Institutional / Bureaucratic Lingo"),
    14: ("Actors", "Generic / Neutral Language"),
    15: ("Context and Concepts", "Institutional / Bureaucratic Lingo"),
    16: ("Context and Concepts", "Generic / Neutral Language"),
    17: ("Actors", "Institutional / Bureaucratic Lingo"),
    18: ("Actors", "Institutional / Bureaucratic Lingo"),
    19: ("Actors", "Generic / Neutral Language"),
    20: ("Context and Concepts", "Institutional / Bureaucratic Lingo"),
    21: ("Actors", "Ideological Framing (Discrediting)"),
    22: ("Actors", "Ideological Framing (Discrediting)"),
    23: ("Actors", "Ideological Framing (Discrediting)"),
    24: ("Actions", "Action-Focused Language"),
    25: ("Actions", "Ideological Framing (Discrediting)"),
    26: ("Context and Concepts", "Ideological Framing (Discrediting)"),
    27: ("Context and Concepts", "Ideological Framing (Discrediting)"),
    28: ("Context and Concepts", "Institutional / Bureaucratic Lingo"),
    29: ("Actors", "Institutional / Bureaucratic Lingo"),
    30: ("Actions", "Institutional / Bureaucratic Lingo"),
    31: ("Context and Concepts", "Ideological Framing (Discrediting)"),
    32: ("Context and Concepts", "Ideological Framing (Discrediting)"),
    33: ("Context and Concepts", "Institutional / Bureaucratic Lingo"),
    34: ("Actions", "Action-Focused Language"),
    35: ("Context and Concepts", "Generic / Neutral Language"),
    36: ("Actions", "Ideological Framing (Discrediting)"),
    37: ("Actors", "Ideological Framing (Discrediting)"),
    38: ("Actions", "Institutional / Bureaucratic Lingo"),
    39: ("Actors", "Generic / Neutral Language"),
    40: ("Context and Concepts", "Generic / Neutral Language"),
    41: ("Actions", "Generic / Neutral Language"),
    42: ("Context and Concepts", "Generic / Neutral Language"),
    43: ("Actors", "Ideological Framing (Discrediting)"),
    44: ("Actions", "Ideological Framing (Discrediting)"),
    45: ("Actors", "Ideological Framing (Discrediting)"),
    46: ("Time", "Generic / Neutral Language"),
    47: ("Actors", "Generic / Neutral Language"),
    48: ("Actions", "Legal Framework"),
    49: ("Context and Concepts", "Ideological Framing (Discrediting)"),
    50: ("Context and Concepts", "Institutional / Bureaucratic Lingo"),
    51: ("Context and Concepts", "Ideological Framing (Discrediting)"),
    52: ("Actions", "Generic / Neutral Language"),
    53: ("Context and Concepts", "Ideological Phrasing (Normalizing)"),
    54: ("Context and Concepts", "Institutional / Bureaucratic Lingo"),
    55: ("Actors", "Generic / Neutral Language"),
    56: ("Documents", "Generic / Neutral Language"),
    57: ("Time", "Generic / Neutral Language"),
    58: ("Actions", "Generic / Neutral Language"),
    59: ("Places", "Generic / Neutral Language"),
    60: ("Places", "Generic / Neutral Language"),
    61: ("Places", "Generic / Neutral Language"),
    62: ("Places", "Generic / Neutral Language"),
    63: ("Context and Concepts", "Institutional / Bureaucratic Lingo"),
    64: ("Actions", "Institutional / Bureaucratic Lingo"),
    65: ("Actions", "Ideological Framing (Discrediting)"),
    66: ("Context and Concepts", "Ideological Framing (Discrediting)"),
    67: ("Context and Concepts", "Ideological Framing (Discrediting)"),
    68: ("Context and Concepts", "Ideological Framing (Discrediting)"),
    69: ("Context and Concepts", "Ideological Framing (Discrediting)"),
    70: ("Actors", "Ideological Framing (Discrediting)"),
    71: ("Actions", "Action-Focused Language"),
    72: ("Actions", "Institutional / Bureaucratic Lingo"),
    73: ("Documents", "Institutional / Bureaucratic Lingo"),
    74: ("Time", "Generic / Neutral Language"),
    75: ("Actors", "Ideological Framing (Discrediting)"),
    76: ("Places", "Generic / Neutral Language"),
    77: ("Context and Concepts", "Ideological Framing (Discrediting)"),
    78: ("Context and Concepts", "Ideological Framing (Discrediting)"),
    79: ("Context and Concepts", "Ideological Framing (Discrediting)"),
    80: ("Context and Concepts", "Ideological Framing (Discrediting)"),
    81: ("Context and Concepts", "Ideological Framing (Discrediting)"),
    82: ("Context and Concepts", "Institutional / Bureaucratic Lingo"),
    83: ("Actions", "Institutional / Bureaucratic Lingo"),
    84: ("Context and Concepts", "Institutional / Bureaucratic Lingo"),
    85: ("Context and Concepts", "Ideological Phrasing (Normalizing)"),
    86: ("Context and Concepts", "Institutional / Bureaucratic Lingo"),
    87: ("Actions", "Ideological Framing (Discrediting)"),
    88: ("Actions", "Ideological Framing (Discrediting)"),
    89: ("Actions", "Action-Focused Language"),
    90: ("Actors", "Generic / Neutral Language"),
    91: ("Actors", "Generic / Neutral Language"),
    92: ("Context and Concepts", "Ideological Phrasing (Normalizing)"),
    93: ("Actors", "Ideological Framing (Discrediting)"),
    94: ("Actors", "Generic / Neutral Language"),
    95: ("Actors", "Generic / Neutral Language"),
    96: ("Context and Concepts", "Ideological Framing (Discrediting)"),
    97: ("Context and Concepts", "Ideological Phrasing (Normalizing)"),
    98: ("Context and Concepts", "Generic / Neutral Language"),
    99: ("Actions", "Action-Focused Language"),
    100: ("Context and Concepts", "Generic / Neutral Language"),
    101: ("Actions", "Ideological Framing (Discrediting)"),
    102: ("Actors", "Generic / Neutral Language"),
    103: ("Actors", "Generic / Neutral Language"),
    104: ("Actions", "Ideological Framing (Discrediting)"),
    105: ("Actions", "Generic / Neutral Language"),
    106: ("Actors", "Ideological Framing (Discrediting)"),
    107: ("Actors", "Ideological Framing (Discrediting)"),
    108: ("Actions", "Ideological Framing (Discrediting)"),
    109: ("Context and Concepts", "Ideological Framing (Discrediting)"),
    110: ("Context and Concepts", "Ideological Phrasing (Normalizing)"),
    111: ("Context and Concepts", "Ideological Phrasing (Normalizing)"),
    112: ("Context and Concepts", "Institutional / Bureaucratic Lingo"),
    113: ("Actions", "Ideological Framing (Discrediting)"),
    114: ("Actors", "Ideological Phrasing (Normalizing)"),
    115: ("Places", "Generic / Neutral Language"),
    116: ("Documents", "Generic / Neutral Language"),
    118: ("Actors", "Ideological Phrasing (Normalizing)"),
    119: ("Actors", "Generic / Neutral Language"),
    120: ("Actions", "Institutional / Bureaucratic Lingo"),
    121: ("Context and Concepts", "Ideological Framing (Discrediting)"),
    122: ("Context and Concepts", "Ideological Framing (Discrediting)"),
    123: ("Actions", "Institutional / Bureaucratic Lingo"),
    124: ("Actors", "Generic / Neutral Language"),
    125: ("Actions", "Ideological Framing (Discrediting)"),
    126: ("Actors", "Ideological Framing (Discrediting)"),
    127: ("Context and Concepts", "Ideological Framing (Discrediting)"),
    128: ("Context and Concepts", "Ideological Framing (Discrediting)"),
    129: ("Context and Concepts", "Ideological Phrasing (Normalizing)"),
    130: ("Context and Concepts", "Ideological Framing (Discrediting)"),
    131: ("Context and Concepts", "Ideological Phrasing (Normalizing)"),
    132: ("Context and Concepts", "Institutional / Bureaucratic Lingo"),
    133: ("Context and Concepts", "Ideological Framing (Discrediting)"),
    134: ("Actions", "Ideological Framing (Discrediting)"),
    135: ("Actions", "Institutional / Bureaucratic Lingo"),
    136: ("Actions", "Ideological Framing (Discrediting)"),
    137: ("Places", "Generic / Neutral Language"),
    138: ("Documents", "Ideological Framing (Discrediting)"),
    139: ("Documents", "Ideological Framing (Discrediting)"),
    140: ("Context and Concepts", "Ideological Framing (Discrediting)"),
    141: ("Context and Concepts", "Institutional / Bureaucratic Lingo"),
    142: ("Actions", "Institutional / Bureaucratic Lingo"),
    143: ("Actions", "Generic / Neutral Language"),
    144: ("Places", "Generic / Neutral Language"),
    145: ("Documents", "Ideological Framing (Discrediting)"),
    146: ("Actions", "Institutional / Bureaucratic Lingo"),
    147: ("Actions", "Ideological Framing (Discrediting)"),
    148: ("Context and Concepts", "Ideological Framing (Discrediting)"),
    149: ("Context and Concepts", "Ideological Framing (Discrediting)"),
    150: ("Context and Concepts", "Institutional / Bureaucratic Lingo"),
    151: ("Context and Concepts", "Ideological Phrasing (Normalizing)"),
    152: ("Actors", "Institutional / Bureaucratic Lingo"),
    153: ("Actions", "Ideological Phrasing (Normalizing)"),
    154: ("Context and Concepts", "Institutional / Bureaucratic Lingo"),
    155: ("Context and Concepts", "Institutional / Bureaucratic Lingo"),
    156: ("Actors", "Generic / Neutral Language"),
    157: ("Actors", "Generic / Neutral Language"),
    158: ("Places", "Generic / Neutral Language"),
    159: ("Places", "Generic / Neutral Language"),
    160: ("Context and Concepts", "Ideological Framing (Discrediting)"),
    161: ("Actions", "Ideological Phrasing (Normalizing)"),
    162: ("Actions", "Ideological Phrasing (Normalizing)"),
    163: ("Places", "Generic / Neutral Language"),
    164: ("Actors", "Ideological Phrasing (Normalizing)"),
    165: ("Actions", "Institutional / Bureaucratic Lingo"),
    166: ("Context and Concepts", "Ideological Phrasing (Normalizing)"),
    167: ("Context and Concepts", "Generic / Neutral Language"),
    168: ("Actions", "Institutional / Bureaucratic Lingo"),
    169: ("Context and Concepts", "Institutional / Bureaucratic Lingo"),
    170: ("Context and Concepts", "Institutional / Bureaucratic Lingo"),
    171: ("Context and Concepts", "Generic / Neutral Language"),
    172: ("Actions", "Action-Focused Language"),
    173: ("Context and Concepts", "Ideological Framing (Discrediting)"),
    174: ("Context and Concepts", "Ideological Phrasing (Normalizing)"),
    175: ("Actors", "Generic / Neutral Language"),
    176: ("Actors", "Generic / Neutral Language"),
    177: ("Actors", "Generic / Neutral Language"),
    178: ("Context and Concepts", "Ideological Framing (Discrediting)"),
    179: ("Actors", "Ideological Framing (Discrediting)"),
    180: ("Context and Concepts", "Generic / Neutral Language"),
    181: ("Context and Concepts", "Generic / Neutral Language"),
    182: ("Context and Concepts", "Ideological Framing (Discrediting)"),
    183: ("Context and Concepts", "Generic / Neutral Language"),
    184: ("Actors", "Ideological Framing (Discrediting)"),
    185: ("Context and Concepts", "Ideological Framing (Discrediting)"),
    186: ("Context and Concepts", "Generic / Neutral Language"),
    187: ("Context and Concepts", "Ideological Phrasing (Normalizing)"),
    188: ("Actors", "Ideological Framing (Discrediting)"),
    189: ("Actions", "Generic / Neutral Language"),
    190: ("Actions", "Action-Focused Language"),
    191: ("Context and Concepts", "Institutional / Bureaucratic Lingo"),
    192: ("Context and Concepts", "Institutional / Bureaucratic Lingo"),
    193: ("Context and Concepts", "Institutional / Bureaucratic Lingo"),
    194: ("Legal Framework", "Generic / Neutral Language"),
    195: ("Actors", "Generic / Neutral Language"),
    196: ("Context and Concepts", "Generic / Neutral Language"),
    197: ("Context and Concepts", "Ideological Framing (Discrediting)"),
    198: ("Actors", "Ideological Framing (Discrediting)"),
    199: ("Context and Concepts", "Generic / Neutral Language"),
    200: ("Actions", "Institutional / Bureaucratic Lingo"),
    201: ("Context and Concepts", "Institutional / Bureaucratic Lingo"),
    202: ("Context and Concepts", "Ideological Framing (Discrediting)"),
    203: ("Context and Concepts", "Ideological Framing (Discrediting)"),
    204: ("Context and Concepts", "Ideological Framing (Discrediting)"),
    205: ("Context and Concepts", "Ideological Framing (Discrediting)"),
    206: ("Context and Concepts", "Ideological Framing (Discrediting)"),
    207: ("Time", "Generic / Neutral Language"),
    208: ("Context and Concepts", "Ideological Framing (Discrediting)"),
    209: ("Actors", "Generic / Neutral Language"),
    210: ("Actors", "Generic / Neutral Language"),
    211: ("Actors", "Ideological Framing (Discrediting)"),
    212: ("Actions", "Action-Focused Language"),
    213: ("Actions", "Ideological Framing (Discrediting)"),
    214: ("Actions", "Ideological Framing (Discrediting)"),
    215: ("Context and Concepts", "Ideological Phrasing (Normalizing)"),
    216: ("Context and Concepts", "Ideological Phrasing (Normalizing)"),
    217: ("Context and Concepts", "Institutional / Bureaucratic Lingo"),
    218: ("Context and Concepts", "Ideological Framing (Discrediting)"),
    219: ("Actors", "Institutional / Bureaucratic Lingo"),
    220: ("Actions", "Institutional / Bureaucratic Lingo"),
    221: ("Actions", "Ideological Framing (Discrediting)"),
    222: ("Actions", "Institutional / Bureaucratic Lingo"),
    223: ("Actions", "Institutional / Bureaucratic Lingo"),
    224: ("Actions", "Ideological Framing (Discrediting)"),
    225: ("Documents", "Ideological Framing (Discrediting)"),
    226: ("Actors", "Institutional / Bureaucratic Lingo"),
    227: ("Actors", "Generic / Neutral Language"),
    228: ("Places", "Generic / Neutral Language"),
    229: ("Places", "Generic / Neutral Language"),
    230: ("Actions", "Institutional / Bureaucratic Lingo"),
    231: ("Context and Concepts", "Ideological Framing (Discrediting)"),
    232: ("Actors", "Ideological Framing (Discrediting)"),
    233: ("Actors", "Ideological Framing (Discrediting)"),
    234: ("Actors", "Ideological Framing (Discrediting)"),
    235: ("Context and Concepts", "Generic / Neutral Language"),
    236: ("Context and Concepts", "Institutional / Bureaucratic Lingo"),
    237: ("Actors", "Institutional / Bureaucratic Lingo"),
    238: ("Actors", "Institutional / Bureaucratic Lingo"),
}


def main():
    segments = json.loads(SEGMENTS_PATH.read_text(encoding="utf-8"))
    assessments = json.loads(ASSESSMENTS_PATH.read_text(encoding="utf-8"))

    rows = []
    for s in segments:
        sec = s["section"]
        if sec not in ASSESSMENT:
            continue
        cat, framing = ASSESSMENT[sec]
        entry_eng = s["entry_eng"]
        entry_rus = s["entry_rus"]
        rows.append({
            "section": sec,
            "entry_eng": entry_eng,
            "entry_rus": entry_rus,
            "content_category": cat,
            "framing": framing,
            "context": s.get("context", entry_eng[:200]),
        })

    assessments["1262_28-32"] = rows
    ASSESSMENTS_PATH.write_text(json.dumps(assessments, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"Written {len(rows)} assessments for 1262_28-32")


if __name__ == "__main__":
    main()
