#!/usr/bin/env python3
"""
Write fresh manual assessment for 1249-80-83.
Based on: taxonomy (7 categories, 5 framing), Russian original, segment list.
Never read GT labels. 1987 KGB Information Report: foreigners in USSR, Canada Nazi campaign, Admiral Nakhimov trial.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SEGMENTS_PATH = ROOT / "data" / "output" / "segments_only_1249-80-83.json"
ASSESSMENTS_PATH = ROOT / "data" / "output" / "agent_assessments.json"

ASSESSMENT = {
    3: ("Documents", "Generic / Neutral Language"),
    4: ("Actors", "Generic / Neutral Language"),
    5: ("Time", "Generic / Neutral Language"),
    6: ("Context and Concepts", "Generic / Neutral Language"),
    7: ("Time", "Generic / Neutral Language"),
    8: ("Documents", "Generic / Neutral Language"),
    9: ("Places", "Generic / Neutral Language"),
    10: ("Context and Concepts", "Generic / Neutral Language"),
    11: ("Context and Concepts", "Generic / Neutral Language"),
    12: ("Actors", "Institutional / Bureaucratic Lingo"),
    13: ("Context and Concepts", "Generic / Neutral Language"),
    14: ("Time", "Generic / Neutral Language"),
    15: ("Documents", "Generic / Neutral Language"),
    16: ("Documents", "Generic / Neutral Language"),
    17: ("Actors", "Institutional / Bureaucratic Lingo"),
    18: ("Actors", "Institutional / Bureaucratic Lingo"),
    19: ("Places", "Generic / Neutral Language"),
    20: ("Context and Concepts", "Generic / Neutral Language"),
    21: ("Context and Concepts", "Ideological Phrasing (Normalizing)"),
    22: ("Actors", "Generic / Neutral Language"),
    23: ("Places", "Generic / Neutral Language"),
    24: ("Actors", "Generic / Neutral Language"),
    25: ("Actors", "Generic / Neutral Language"),
    26: ("Actors", "Generic / Neutral Language"),
    27: ("Context and Concepts", "Generic / Neutral Language"),
    28: ("Actors", "Institutional / Bureaucratic Lingo"),
    29: ("Context and Concepts", "Generic / Neutral Language"),
    30: ("Places", "Generic / Neutral Language"),
    31: ("Actors", "Generic / Neutral Language"),
    32: ("Actors", "Generic / Neutral Language"),
    33: ("Actors", "Generic / Neutral Language"),
    34: ("Actors", "Generic / Neutral Language"),
    35: ("Actions", "Generic / Neutral Language"),
    36: ("Actors", "Generic / Neutral Language"),
    37: ("Actors", "Generic / Neutral Language"),
    38: ("Actors", "Generic / Neutral Language"),
    39: ("Actions", "Generic / Neutral Language"),
    40: ("Actors", "Generic / Neutral Language"),
    41: ("Context and Concepts", "Generic / Neutral Language"),
    42: ("Places", "Generic / Neutral Language"),
    43: ("Places", "Generic / Neutral Language"),
    44: ("Places", "Generic / Neutral Language"),
    45: ("Places", "Generic / Neutral Language"),
    46: ("Places", "Generic / Neutral Language"),
    47: ("Places", "Generic / Neutral Language"),
    48: ("Context and Concepts", "Generic / Neutral Language"),
    49: ("Places", "Generic / Neutral Language"),
    50: ("Context and Concepts", "Generic / Neutral Language"),
    51: ("Context and Concepts", "Generic / Neutral Language"),
    52: ("Context and Concepts", "Generic / Neutral Language"),
    53: ("Context and Concepts", "Generic / Neutral Language"),
    54: ("Places", "Generic / Neutral Language"),
    55: ("Places", "Generic / Neutral Language"),
    56: ("Places", "Generic / Neutral Language"),
    57: ("Places", "Generic / Neutral Language"),
    58: ("Places", "Generic / Neutral Language"),
    59: ("Places", "Generic / Neutral Language"),
    60: ("Context and Concepts", "Generic / Neutral Language"),
    61: ("Places", "Generic / Neutral Language"),
    62: ("Places", "Generic / Neutral Language"),
    63: ("Places", "Generic / Neutral Language"),
    64: ("Context and Concepts", "Generic / Neutral Language"),
    65: ("Context and Concepts", "Generic / Neutral Language"),
    66: ("Places", "Generic / Neutral Language"),
    67: ("Places", "Generic / Neutral Language"),
    68: ("Places", "Generic / Neutral Language"),
    69: ("Places", "Generic / Neutral Language"),
    70: ("Places", "Generic / Neutral Language"),
    71: ("Context and Concepts", "Generic / Neutral Language"),
    72: ("Context and Concepts", "Generic / Neutral Language"),
    73: ("Places", "Generic / Neutral Language"),
    74: ("Places", "Generic / Neutral Language"),
    75: ("Places", "Generic / Neutral Language"),
    76: ("Places", "Generic / Neutral Language"),
    77: ("Places", "Generic / Neutral Language"),
    78: ("Places", "Generic / Neutral Language"),
    79: ("Places", "Generic / Neutral Language"),
    80: ("Places", "Generic / Neutral Language"),
    81: ("Context and Concepts", "Generic / Neutral Language"),
    82: ("Places", "Generic / Neutral Language"),
    83: ("Places", "Generic / Neutral Language"),
    84: ("Places", "Generic / Neutral Language"),
    85: ("Places", "Generic / Neutral Language"),
    86: ("Context and Concepts", "Generic / Neutral Language"),
    87: ("Context and Concepts", "Generic / Neutral Language"),
    88: ("Context and Concepts", "Ideological Phrasing (Normalizing)"),
    89: ("Context and Concepts", "Generic / Neutral Language"),
    90: ("Context and Concepts", "Generic / Neutral Language"),
    91: ("Context and Concepts", "Generic / Neutral Language"),
    92: ("Context and Concepts", "Generic / Neutral Language"),
    93: ("Context and Concepts", "Generic / Neutral Language"),
    94: ("Context and Concepts", "Institutional / Bureaucratic Lingo"),
    95: ("Actions", "Generic / Neutral Language"),
    96: ("Places", "Generic / Neutral Language"),
    97: ("Actors", "Ideological Framing (Discrediting)"),
    98: ("Actions", "Institutional / Bureaucratic Lingo"),
    99: ("Actors", "Institutional / Bureaucratic Lingo"),
    100: ("Actions", "Ideological Framing (Discrediting)"),
    101: ("Actors", "Ideological Phrasing (Normalizing)"),
    102: ("Context and Concepts", "Generic / Neutral Language"),
    103: ("Places", "Generic / Neutral Language"),
    104: ("Context and Concepts", "Generic / Neutral Language"),
    105: ("Actors", "Ideological Framing (Discrediting)"),
    106: ("Actors", "Ideological Framing (Discrediting)"),
    107: ("Time", "Generic / Neutral Language"),
    108: ("Places", "Generic / Neutral Language"),
    109: ("Actions", "Action-Focused Language"),
    110: ("Actors", "Generic / Neutral Language"),
    111: ("Actions", "Generic / Neutral Language"),
    112: ("Context and Concepts", "Ideological Framing (Discrediting)"),
    113: ("Documents", "Institutional / Bureaucratic Lingo"),
    114: ("Time", "Generic / Neutral Language"),
    115: ("Context and Concepts", "Institutional / Bureaucratic Lingo"),
    116: ("Actors", "Institutional / Bureaucratic Lingo"),
    117: ("Time", "Generic / Neutral Language"),
    118: ("Actors", "Generic / Neutral Language"),
    119: ("Actions", "Generic / Neutral Language"),
    120: ("Context and Concepts", "Generic / Neutral Language"),
    121: ("Context and Concepts", "Generic / Neutral Language"),
    122: ("Legal Framework", "Generic / Neutral Language"),
    123: ("Actions", "Generic / Neutral Language"),
    124: ("Actors", "Ideological Framing (Discrediting)"),
    125: ("Context and Concepts", "Institutional / Bureaucratic Lingo"),
    126: ("Actions", "Generic / Neutral Language"),
    127: ("Context and Concepts", "Generic / Neutral Language"),
    128: ("Context and Concepts", "Generic / Neutral Language"),
    129: ("Context and Concepts", "Ideological Framing (Discrediting)"),
    130: ("Context and Concepts", "Generic / Neutral Language"),
    131: ("Context and Concepts", "Generic / Neutral Language"),
    132: ("Places", "Generic / Neutral Language"),
    133: ("Legal Framework", "Generic / Neutral Language"),
    134: ("Actions", "Institutional / Bureaucratic Lingo"),
    135: ("Documents", "Generic / Neutral Language"),
    136: ("Actors", "Ideological Framing (Discrediting)"),
    137: ("Context and Concepts", "Institutional / Bureaucratic Lingo"),
    138: ("Actions", "Generic / Neutral Language"),
    139: ("Actors", "Generic / Neutral Language"),
    140: ("Actions", "Generic / Neutral Language"),
    141: ("Legal Framework", "Generic / Neutral Language"),
    142: ("Context and Concepts", "Generic / Neutral Language"),
    143: ("Actors", "Generic / Neutral Language"),
    144: ("Time", "Generic / Neutral Language"),
    145: ("Actions", "Action-Focused Language"),
    146: ("Context and Concepts", "Institutional / Bureaucratic Lingo"),
    147: ("Legal Framework", "Generic / Neutral Language"),
    148: ("Legal Framework", "Generic / Neutral Language"),
    149: ("Actions", "Generic / Neutral Language"),
    150: ("Actors", "Ideological Framing (Discrediting)"),
    151: ("Context and Concepts", "Generic / Neutral Language"),
    152: ("Places", "Generic / Neutral Language"),
    153: ("Places", "Generic / Neutral Language"),
    154: ("Actors", "Institutional / Bureaucratic Lingo"),
    155: ("Actions", "Institutional / Bureaucratic Lingo"),
    156: ("Context and Concepts", "Institutional / Bureaucratic Lingo"),
    157: ("Documents", "Generic / Neutral Language"),
    158: ("Context and Concepts", "Ideological Framing (Discrediting)"),
    159: ("Time", "Generic / Neutral Language"),
    160: ("Context and Concepts", "Institutional / Bureaucratic Lingo"),
    161: ("Context and Concepts", "Generic / Neutral Language"),
    162: ("Context and Concepts", "Generic / Neutral Language"),
    163: ("Documents", "Generic / Neutral Language"),
    164: ("Documents", "Generic / Neutral Language"),
    165: ("Places", "Generic / Neutral Language"),
    166: ("Time", "Generic / Neutral Language"),
    167: ("Context and Concepts", "Generic / Neutral Language"),
    168: ("Actors", "Generic / Neutral Language"),
    169: ("Actors", "Institutional / Bureaucratic Lingo"),
    170: ("Actions", "Institutional / Bureaucratic Lingo"),
    171: ("Actors", "Generic / Neutral Language"),
    172: ("Documents", "Generic / Neutral Language"),
    173: ("Actors", "Generic / Neutral Language"),
    174: ("Actors", "Generic / Neutral Language"),
    175: ("Time", "Generic / Neutral Language"),
    176: ("Actors", "Generic / Neutral Language"),
    177: ("Documents", "Generic / Neutral Language"),
    178: ("Actors", "Generic / Neutral Language"),
    179: ("Actors", "Generic / Neutral Language"),
    180: ("Time", "Generic / Neutral Language"),
    181: ("Legal Framework", "Institutional / Bureaucratic Lingo"),
    182: ("Legal Framework", "Generic / Neutral Language"),
    183: ("Context and Concepts", "Generic / Neutral Language"),
    184: ("Context and Concepts", "Generic / Neutral Language"),
    185: ("Actions", "Institutional / Bureaucratic Lingo"),
    186: ("Context and Concepts", "Generic / Neutral Language"),
    187: ("Context and Concepts", "Generic / Neutral Language"),
    188: ("Documents", "Institutional / Bureaucratic Lingo"),
    189: ("Documents", "Institutional / Bureaucratic Lingo"),
    190: ("Time", "Generic / Neutral Language"),
    191: ("Actors", "Generic / Neutral Language"),
    192: ("Actors", "Generic / Neutral Language"),
    193: ("Actions", "Institutional / Bureaucratic Lingo"),
    194: ("Context and Concepts", "Generic / Neutral Language"),
    195: ("Context and Concepts", "Generic / Neutral Language"),
    196: ("Context and Concepts", "Generic / Neutral Language"),
    197: ("Context and Concepts", "Generic / Neutral Language"),
    198: ("Context and Concepts", "Generic / Neutral Language"),
    199: ("Context and Concepts", "Generic / Neutral Language"),
    200: ("Actions", "Generic / Neutral Language"),
    201: ("Context and Concepts", "Generic / Neutral Language"),
    202: ("Actions", "Institutional / Bureaucratic Lingo"),
    203: ("Context and Concepts", "Generic / Neutral Language"),
    204: ("Context and Concepts", "Generic / Neutral Language"),
    205: ("Context and Concepts", "Generic / Neutral Language"),
    206: ("Actors", "Institutional / Bureaucratic Lingo"),
    207: ("Actors", "Institutional / Bureaucratic Lingo"),
    208: ("Actors", "Institutional / Bureaucratic Lingo"),
    209: ("Context and Concepts", "Institutional / Bureaucratic Lingo"),
    210: ("Context and Concepts", "Institutional / Bureaucratic Lingo"),
    211: ("Context and Concepts", "Generic / Neutral Language"),
    212: ("Documents", "Generic / Neutral Language"),
    213: ("Context and Concepts", "Ideological Framing (Discrediting)"),
    214: ("Actors", "Generic / Neutral Language"),
    215: ("Context and Concepts", "Generic / Neutral Language"),
    216: ("Actors", "Generic / Neutral Language"),
    217: ("Time", "Generic / Neutral Language"),
    218: ("Context and Concepts", "Generic / Neutral Language"),
    219: ("Actors", "Generic / Neutral Language"),
    220: ("Places", "Generic / Neutral Language"),
    221: ("Actors", "Generic / Neutral Language"),
    222: ("Context and Concepts", "Generic / Neutral Language"),
    223: ("Actors", "Generic / Neutral Language"),
    224: ("Places", "Generic / Neutral Language"),
    225: ("Context and Concepts", "Generic / Neutral Language"),
    226: ("Context and Concepts", "Generic / Neutral Language"),
    227: ("Context and Concepts", "Generic / Neutral Language"),
    228: ("Actions", "Generic / Neutral Language"),
    229: ("Context and Concepts", "Generic / Neutral Language"),
    230: ("Actors", "Generic / Neutral Language"),
    231: ("Context and Concepts", "Generic / Neutral Language"),
    232: ("Actors", "Institutional / Bureaucratic Lingo"),
    233: ("Context and Concepts", "Generic / Neutral Language"),
    234: ("Context and Concepts", "Generic / Neutral Language"),
    235: ("Actions", "Institutional / Bureaucratic Lingo"),
    236: ("Context and Concepts", "Institutional / Bureaucratic Lingo"),
    237: ("Context and Concepts", "Institutional / Bureaucratic Lingo"),
    238: ("Actors", "Institutional / Bureaucratic Lingo"),
    239: ("Actors", "Generic / Neutral Language"),
}


def main():
    segments = json.loads(SEGMENTS_PATH.read_text(encoding="utf-8"))
    assessments = json.loads(ASSESSMENTS_PATH.read_text(encoding="utf-8"))

    rows = []
    for s in segments:
        sec = s["section"]
        if sec not in ASSESSMENT:
            continue
        cat, framing = ASSESSMENT[sec]
        entry_eng = s["entry_eng"].replace("n\\a", "n/a")
        entry_rus = s["entry_rus"]
        rows.append({
            "section": sec,
            "entry_eng": entry_eng,
            "entry_rus": entry_rus,
            "content_category": cat,
            "framing": framing,
            "context": s.get("context", entry_eng[:200]).replace("n\\a", "n/a"),
        })

    assessments["1249-80-83"] = rows
    ASSESSMENTS_PATH.write_text(json.dumps(assessments, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"Written {len(rows)} assessments for 1249-80-83")


if __name__ == "__main__":
    main()
